/* 
 * intquit.c
 * 
 * Catch the SIGINT and SIGQUIT signals, which are normally 
 * generated by the `Control-C`(^C) and `Control-\`(^\) 
 * respectively.
 * 
 * Note that although we use signal() to establish signal 
 * handlers in this program, the use of sigaction() is always
 * preferable for this task.
 * 
 * gcc -I ../lib/ ../lib/error_functions.c intquit.c -o intquit
 */
#include <signal.h>
#include "tlpi_hdr.h"

static void 
sigHandler(int sig) {
    static int count = 0;

    /* Unsafe: this handler uses non-async-signal-safe functions:
     * (printf(), exit(), ...)
     */
    if (sig == SIGINT) {
        count++;
        printf("Caught SIGINT (%d)\n", count);
        return;
    }
    
    /* Must be a SIGQUIT - print a message and terminate the process */
    printf("Caught a SIGQUIT - that' all folks!\n");
    exit(EXIT_SUCCESS);
} 

int 
main(int argc, char *argv[]) 
{
    /* Establish same handler for SIGINT and SIGQUIT. 
     * Here we use the signal() API to esatblish a signal
     * handler, but sigaction() is the (strongly) preferred API
     * for this task.
     */
    if (signal(SIGINT, sigHandler) == SIG_ERR) {
        errExit("signal");
    }
    
    if (signal(SIGQUIT, sigHandler) == SIG_ERR) {
        errExit("signal");
    }

    for (;;) {
        pause();
    }
}